### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by emog** [Stremio/stremio-core-swift#4]
Hi @AlvinHV,

Could you write in the README how to use this library ? I don't see any requests at all there. It will be helpful.

I tried to add the library in the Package Dependencies but got lost in "how to use" it part.

Thank you.

**Comment by AlvinHV** [comment]
This is also SPM package. Add it using xcode. I will fix readme in the future

**Comment by emog** [comment]
> This is also SPM package. Add it using xcode. I will fix readme in the future

I know that it's SPM package but it will be helpful to know how to use. Does it handle requests to Stremio API and map them to models.

**Comment by AlvinHV** [comment]
Stremio-core handles almost all of Stremio’s client logic, including API fetches and processing add-ons. After all the data is processed from the add-ons and Stremio’s server, it sends a protobuf class, which UIKit processes into visible elements. Essentially, it works like this: UI (UIKit) → (stremio-core-apple) → unprocessed data.

You can take a look at the StremioApi file, which contains most of the APIs used by the Android TV app. Keep in mind that it’s unfinished and there are several things missing.
