### ISSUE TITLE
While building for tvOS Simulator, no library for this platform was found in 

### ISSUE THREAD

**Issue by emog** [Stremio/stremio-core-swift#7]
I got error "While building for tvOS Simulator, no library for this platform was found in '/Users/egeorgiev/Library/Developer/Xcode/DerivedData/Stremio-ehyfhtijmvvkhgacvdsezhjrdgzz/SourcePackages/artifacts/stremio-core-swift/XCFramework/StremioCore.xcframework'."

It's new tvOS project and added the library via the Package Dependencies.

**Comment by AlvinHV** [comment]
Fixed! Update version to 1.2.62 and it should work for tvos-sim both x86_64 and arm64 platforms. Let me know it runs successfully

**Comment by emog** [comment]
> Fixed! Update version to 1.2.62 and it should work for tvos-sim both x86_64 and arm64 platforms. Let me know it runs successfully

Now I don't have any issues when I build the application but have issues when try to use it the app crashes (not just an error)

thread '<unnamed>' panicked at src/commonMain/rust/stremio_core_apple.rs:171:10:
RUNTIME not initialized
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /Users/alvin/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind

It seems that it's looking for your path for rust.

I'm trying:

`StremioCore.StremioApi.Login(email: "someemail@gmail.com", password: "adasdas") { result in
                switch result {
                case .success(let userAuthenticated):
                    // Handle successful authentication
                    print(userAuthenticated)
                case .failure(let error):
                    // Handle login failure
                    print(error)
                }
            }`

**Comment by AlvinHV** [comment]
Could you enable RUST_BACKTRACE using setenv command? This would point me where problem is

**Comment by emog** [comment]
> Could you enable RUST_BACKTRACE using setenv command? This would point me where problem is

My user is not alvin. Somehow it wants to use your path not mine. It's hardcoded somewhere.

**Comment by AlvinHV** [comment]
Because it's compiled in my device it shows my path. Thats how rust works even on release apparently. So please share full path

**Comment by AlvinHV** [comment]
This issue caused by using Core without initializing. Please call `Core.initialize() ` before executing any type of API. Otherwise it will crash

**Comment by emog** [comment]
> This issue caused by using Core without initializing. Please call `Core.initialize() ` before executing any type of API. Otherwise it will crash

Could you send me some contact information, so I could reach you ?

**Comment by AlvinHV** [comment]
Could i ask what topic you want to discuss?

**Comment by emog** [comment]
> Could i ask what topic you want to discuss?

@AlvinHV - It's not so clear how to use the library at all. I needed some information and wanted to have a quick chat with you about that and to improve the README file but never mind. I gave up on this because it's so unreasonable with all those middle layer things.  I cant event map the response of some request to the real object. I know why Stremio makes it in this way but it's not applicable for Swift well enough or something is not converted in a right way. No clear documentation how the library is included.  Adding @Ivshti  to see my feedback.

**Comment by AlvinHV** [comment]
Stremio-core-swift is a fork of stremio-core-kotlin and doesn’t include stremioApi.kt in its library. It takes time for me to analyze and clarify its functionality. Additionally, having some background knowledge about Stremio’s internal APIs is necessary to use it effectively, which is beyond the scope of stremio-core-swift. Regarding mapping responses to objects, I haven’t encountered issues with the implemented APIs so far. Here is a [preview](https://imgur.com/a/i1XhTZ2) of my work before joining Stremio.

Understanding and completing the implementation will require more time, so it might be best to wait for the official release. (If @Ivshti could give you access to private repo fell free to experiment with stremio-apple)

**Comment by emog** [comment]
> Stremio-core-swift is a fork of stremio-core-kotlin and doesn’t include stremioApi.kt in its library. It takes time for me to analyze and clarify its functionality. Additionally, having some background knowledge about Stremio’s internal APIs is necessary to use it effectively, which is beyond the scope of stremio-core-swift. Regarding mapping responses to objects, I haven’t encountered issues with the implemented APIs so far. Here is a [preview](https://imgur.com/a/i1XhTZ2) of my work before joining Stremio.
> 
> Understanding and completing the implementation will require more time, so it might be best to wait for the official release. (If @Ivshti could give you access to private repo fell free to experiment with stremio-apple)

So you will create an apple tv app at some point. Is that the case ?
