### ISSUE TITLE
Please Stremio ipa version iOS and version tvOS 

### ISSUE THREAD

**Issue by popcorn2024ok** [Stremio/stremio-core-swift#8]
When will the versions of Stremio be released for iOS and TVOS, the ipa or with Xcode in the please  ipa

**Comment by AlvinHV** [comment]
sorry to disappoint you, but information about release date and iPA is incorrect. We never give release date, we just release it instead. Please wait for official announcement.

**Comment by popcorn2024ok** [comment]
> sorry to disappoint you, but information about release date and iPA is incorrect. We never give release date, we just release it instead. Please wait for official announcement.

Ok let's wait for the announcement, friend

**Comment by popcorn2024ok** [comment]
> sorry to disappoint you, but information about release date and iPA is incorrect. We never give release date, we just release it instead. Please wait for official announcement.

Ok, let's wait for the announcement, friend
